query GetArchivedThreads($boardKey: String!, $page: Int!) {
  board(boardKey: $boardKey) {
    id
    archivedThreads(page: $page) {
      threadNumber
      title
      responseCount
      lastModified
      boardId
    }
  }
}
